/**
 * App-wide limits, Zagreb defaults, and integration tuning — single source of truth.
 */

/** Step 1: user must enter between 2 and 3 candidate apartments */
export const MIN_APARTMENT_CANDIDATES = 2;
export const MAX_APARTMENT_CANDIDATES = 3;

/** Rough utilities when user has no bills yet — €/m²/month (placeholder heuristic) */
export const ZAGREB_DEFAULT_UTILITIES_EUROS_PER_SQUARE_METER_MONTH = 0.85;

/** Places API radial search for QoL amenities */
export const NEIGHBORHOOD_QUALITY_SEARCH_RADIUS_METERS = 800;

/** Max extra narrative length from Gemini (chars) */
export const GEMINI_WINNER_SUMMARY_MAX_CHARS = 2000;

/** localStorage key for cross-step wizard state */
export const LOCAL_STORAGE_COMPARISON_SESSION_KEY = "stanko-trazic-comparison-session";

/** Firestore collection name for saved comparisons */
export const FIRESTORE_COMPARISONS_COLLECTION = "zagreb-apartment-comparisons";

/** ZET monthly pass placeholder when transit is tram/bus (€/month) */
export const ZAGREB_ZET_MONTHLY_PASS_EUROS = 30;

/** Zagreb public bike (bajs) seasonal pass placeholder (€/month averaged) */
export const ZAGREB_BIKE_MONTHLY_EQUIVALENT_EUROS = 5;

/** Default fuel cost per km when driving (€) — zone/refinement later */
export const DEFAULT_FUEL_COST_EUROS_PER_KM = 0.12;

/**
 * When Directions returns no route (e.g. bicycling unsupported) or fails,
 * use this single-leg surrogate so comparisons still complete. ~24 min / 4.2 km one-way.
 */
export const DIRECTIONS_FALLBACK_ONE_WAY_DURATION_SECONDS = 24 * 60;
export const DIRECTIONS_FALLBACK_ONE_WAY_DISTANCE_METERS = 4200;

/** Google Directions API (legacy JSON) */
export const GOOGLE_DIRECTIONS_JSON_BASE =
  "https://maps.googleapis.com/maps/api/directions/json";

/** Google Geocoding API (JSON) — same key as Places/Directions when APIs enabled */
export const GOOGLE_GEOCODE_JSON_BASE =
  "https://maps.googleapis.com/maps/api/geocode/json";

/** Bias geocoding to Croatia for Zagreb-centric flows */
export const GEOCODE_COUNTRY_COMPONENT = "country:HR";

/** Places API (New) — nearby search */
export const GOOGLE_PLACES_SEARCH_NEARBY_URL =
  "https://places.googleapis.com/v1/places:searchNearby";

/** Places API (New) — autocomplete (server proxy for Person A) */
export const GOOGLE_PLACES_AUTOCOMPLETE_URL =
  "https://places.googleapis.com/v1/places:autocomplete";

/**
 * Field mask for autocomplete — no spaces (Google requirement).
 * @see https://developers.google.com/maps/documentation/places/web-service/place-autocomplete
 */
export const PLACES_AUTOCOMPLETE_FIELD_MASK =
  "suggestions.placePrediction.placeId,suggestions.placePrediction.text,suggestions.placePrediction.structuredFormat";

/** Bias suggestions toward Zagreb / NW Croatia */
export const ZAGREB_AUTOCOMPLETE_CENTER_LATITUDE = 45.815;
export const ZAGREB_AUTOCOMPLETE_CENTER_LONGITUDE = 15.9819;
export const ZAGREB_AUTOCOMPLETE_BIAS_RADIUS_METERS = 50000;

export const PLACES_AUTOCOMPLETE_REGION_CODES = ["hr"] as const;

export const PLACES_AUTOCOMPLETE_MIN_INPUT_LENGTH = 2;
export const PLACES_AUTOCOMPLETE_MAX_INPUT_LENGTH = 200;

/** IETF BCP-47 language for autocomplete labels */
export const PLACES_AUTOCOMPLETE_LANGUAGE_CODE = "hr";

/** Google session token max length (UUID hex is typical) */
export const PLACES_AUTOCOMPLETE_SESSION_TOKEN_MAX_LENGTH = 128;

/** Cap per category for Places nearby (API max 20) */
export const NEIGHBORHOOD_NEARBY_MAX_RESULT_COUNT = 20;

/** Field mask for nearby: ids only (minimize payload) */
export const PLACES_NEARBY_FIELD_MASK = "places.id";

/** Included types for “shops” bucket (Places type enums) */
export const NEIGHBORHOOD_SHOP_PLACE_TYPES = [
  "supermarket",
  "convenience_store",
  "store",
  "shopping_mall",
] as const;

export const NEIGHBORHOOD_PARK_PLACE_TYPES = ["park"] as const;

export const NEIGHBORHOOD_PHARMACY_PLACE_TYPES = ["pharmacy"] as const;

export const NEIGHBORHOOD_CAFE_PLACE_TYPES = ["cafe", "coffee_shop"] as const;

/** Valid Gemini parking zone responses */
export const PARKING_ZONE_VALID_CODES = ["1", "2", "3", "4.1", "4.2"] as const;

/** Gemini model id for REST generateContent (AI Studio; avoid deprecated 2.0-flash for new keys) */
export const GEMINI_GENERATE_CONTENT_MODEL = "gemini-2.5-flash";

/** Gemini REST API base (v1beta) */
export const GEMINI_REST_API_BASE =
  "https://generativelanguage.googleapis.com/v1beta/models";
/** Average working days per month for commute cost projection */
export const WORKING_DAYS_PER_MONTH = 22;

/** One-way trips per working day (home → work, work → home) */
export const COMMUTE_ROUND_TRIPS_PER_DAY = 2;

/** Zagreb parking zone monthly pass prices (€) — official rates */
export const PARKING_ZONE_MONTHLY_EUROS: Record<string, number> = {
  "1": 95.60,
  "2": 47.8,
  "3": 17,
  "4.1": 13.3,
  "4.2": 26.5,
};

/** Fallback when apartment is outside any paid parking zone */
export const PARKING_NO_ZONE_DEFAULT_EUROS = 0;

/** QoL scoring weights per amenity category (relative importance) */
export const QOL_WEIGHT_SHOPS = 3;
export const QOL_WEIGHT_PARKS = 4;
export const QOL_WEIGHT_PHARMACIES = 2;
export const QOL_WEIGHT_CAFES = 1;

/** Count at which an amenity category is considered fully saturated */
export const QOL_SATURATION_COUNT = 10;

/**
 * Official Zagreb parking zone street lists (source: Zagrebparking).
 * Zone I + I.1 + I.2 share the same monthly pass price.
 * Zone II (II.1 + II.2 + II.3) share the same price.
 * Used to build the Gemini parking zone classification prompt.
 */
export const PARKING_ZONE_1_STREETS = [
  "Arnoldova ulica",
  "Bakačeva ulica",
  "Berislavićeva ulica",
  "Bogovićeva ulica",
  "Bosanska ulica",
  "Boškovićeva ulica",
  "Britanski trg",
  "Dalmatinska ulica",
  "Dolac",
  "Draškovićeva ulica",
  "Đorđićeva ulica",
  "Europski trg",
  "Fišerova ulica",
  "Frankopanska ulica",
  "Gajeva ulica",
  "Gundulićeva ulica",
  "Gupčeva zvijezda",
  "Haulikova ulica",
  "Ilica (zona I: od Trga bana Josipa Jelačića do Ulice Republike Austrije)",
  "Jukićeva ulica",
  "Jurišićeva ulica",
  "Jurkovićeva ulica",
  "Kačićeva ulica",
  "Kaptol",
  "Katančićeva ulica",
  "Kordunska ulica",
  "Kožarska ulica",
  "Krajiška ulica",
  "Krvavi most",
  "Kožarske stube",
  "Kamaufova ulica",
  "Kurelčeva ulica",
  "Magdićeve stube",
  "Mala ulica",
  "Margaretska ulica",
  "Martićeva ulica",
  "Masarykova ulica",
  "Medulićeva ulica",
  "Medvedgradska ulica",
  "Medveščak",
  "Mihanovićeva ulica",
  "Mlinarska cesta",
  "Mrazovićeva ulica",
  "Nova Ves",
  "Obrtnički prolaz",
  "Opatovina",
  "Palmotićeva ulica",
  "Pantovčak",
  "Petrinjska ulica",
  "Petrova ulica",
  "Pierottijeva ulica",
  "Pod zidom",
  "Praška ulica",
  "Preradovićeva ulica",
  "Prilaz Gjure Deželića",
  "Primorska ulica",
  "Prolaz Jurja Ratkaja",
  "Prolaz sestara Baković",
  "Radnički dol",
  "Ribnjak",
  "Rokov perivoj",
  "Rokova ulica",
  "Rooseveltov trg",
  "Savska cesta",
  "Skalinska ulica",
  "Streljačka ulica",
  "Stube Franje Ivekovića",
  "Stube Josipa Schlossera",
  "Šalata",
  "Šenoina ulica",
  "Tkalčićeva ulica",
  "Trg Ante Starčevića",
  "Trg bana Josipa Jelačića",
  "Trg Drage Iblera",
  "Trg Eugena Kvaternika",
  "Trg hrvatskih velikana",
  "Trg Ivana, Antuna i Vladimira Mažuranića",
  "Trg Josipa Jurja Strossmayera",
  "Trg Josipa Langa",
  "Trg kralja Petra Krešimira IV.",
  "Trg kralja Petra Svačića",
  "Trg kralja Tomislava",
  "Trg Marka Marulića",
  "Trg Nikole Zrinskog",
  "Trg Petra Petretića",
  "Trg Petra Preradovića",
  "Trg Republike Hrvatske",
  "Trg svibanjskih žrtava 1995.",
  "Trg Vladka Mačeka",
  "Trg žrtava fašizma",
  "Ulica Adolfa Vebera",
  "Ulica Andrije Hebranga",
  "Ulica Ante Kovačića",
  "Ulica Antuna Bauera",
  "Ulica Antuna Heinza",
  "Ulica Antuna Vramca",
  "Ulica Antuna Vrančića",
  "Ulica Augusta Cesarca",
  "Ulica Baltazara Bogišića",
  "Ulica Baltazara Dvorničića",
  "Ulica Bartula Kašića",
  "Ulica baruna Trenka",
  "Ulica Benedikta Vinkovića",
  "Ulica biskupa Galjufa",
  "Ulica Blaža Šoštarića",
  "Ulica Crvenog križa",
  "Ulica Cvjetka Rubetića",
  "Ulica Đure Crnatka",
  "Ulica Eduarda Suhina",
  "Ulica Eleonore Patačić",
  "Ulica Erazma Barčića",
  "Ulica Eugena Kumičića",
  "Ulica fra Filipa Grabovca",
  "Ulica Frana Vrbanića",
  "Ulica Frane Bulića",
  "Ulica Frane Petrića",
  "Ulica Franje Hochmanna",
  "Ulica Gaje Bulata",
  "Ulica Grge Tuškana",
  "Ulica Grgura Ninskog",
  "Ulica Henrika Degena",
  "Ulica Hrvoja Vukčića",
  "Ulica Isidora Kršnjavoga",
  "Ulica Ivana Banjavčića",
  "Ulica Ivana Belostenca",
  "Ulica Ivana Dežmana",
  "Ulica Ivana Gorana Kovačića",
  "Ulica Ivana Kukuljevića",
  "Ulica Ivana Lepušića",
  "Ulica Ivana Perkovca",
  "Ulica Ivana Šveara",
  "Ulica Ivana Znike",
  "Ulica Ive Mallina",
  "Ulica Jakova Gotovca",
  "Ulica Josipa Eugena Tomića",
  "Ulica Josipa Runjanina",
  "Ulica Josipa Torbara",
  "Ulica Jurja Biankinija",
  "Ulica Jurja Branjuga",
  "Ulica Jurja Križanića",
  "Ulica Jurja Plemića",
  "Ulica Jurja Žerjavića",
  "Ulica kneza Borne",
  "Ulica kneza Branimira",
  "Ulica kneza Domagoja",
  "Ulica kneza Mislava",
  "Ulica kneza Mutimira",
  "Ulica kneza Trpimira",
  "Ulica kneza Višeslava",
  "Ulica Koste Vojnovića",
  "Ulica kralja Držislava",
  "Ulica kralja Stjepana Tvrtka",
  "Ulica kralja Zvonimira",
  "Ulica kraljice Jelene",
  "Ulica Ljudevita Farkaša Vukotinovića",
  "Ulica Ljudevita Posavskog",
  "Ulica Marijana Derenčina",
  "Ulica Marka Stančića",
  "Ulica Matice hrvatske",
  "Ulica Matije Mesića",
  "Ulica Matka Laginje",
  "Ulica Mihovila Pavlinovića",
  "Ulica Mije Sinkovića",
  "Ulica Milana Amruša",
  "Ulica Milana Makanca",
  "Ulica Natka Nodila",
  "Ulica neznane junakinje",
  "Ulica Nike Grškovića",
  "Ulica Nikole Tesle",
  "Ulica Nikole Tomašića",
  "Ulica Paškala Buconjića",
  "Ulica Pavla Hatza",
  "Ulica Pavla Šubića",
  "Ulica Petra i Tome Erdödyja",
  "Ulica Petra Kružića",
  "Ulica popa Dukljanina",
  "Ulica Račkoga",
  "Ulica Radoslava Lopašića",
  "Ulica Stjepana Širole",
  "Ulica Sv. Preobraženja",
  "Ulica Šandora Brešćenskoga",
  "Ulica Škendera Fabkovića",
  "Ulica Tadije Smičiklasa",
  "Ulica Tome Gajdeka",
  "Ulica Tome Mikloušića",
  "Ulica Vatroslava Jagića",
  "Ulica Vjekoslava Heinzela",
  "Ulica Vjekoslava Klaića",
  "Ulica Vjenceslava Novaka",
  "Ulica Vladimira Nazora",
  "Varšavska ulica",
  "Vlaška ulica",
  "Vodnikova ulica",
  "Vončinina ulica",
  "Zamenhofova ulica",
  "Zavojna ulica",
  "Zavrtnica",
  "Zvonarnička ulica",
  "Demetrova ulica",
  "Dubravkin put",
  "Dverce",
  "Gradec",
  "Grič",
  "Ilirski trg",
  "Jezuitski trg",
  "Jurjevska ulica",
  "Kamenita ulica",
  "Kapucinske stube",
  "Lisinskoga ulica",
  "Mlinske stube",
  "Mesnička ulica",
  "Mletačka ulica",
  "Opatička ulica",
  "Strossmayerovo šetalište",
  "Stube Ivana Zakmardija",
  "Trg Franje Markovića",
  "Trg Katarine Zrinske",
  "Trg sv. Marka",
  "Ulica 29. listopada 1918.",
  "Ulica Ambroza i Klotilde Vranyczany",
  "Ulica Antuna G. Matoša",
  "Ulica Đure Basarička",
  "Golubovac",
  "Ulica Josipa Freudenreicha",
  "Ulica Josipa Kuševića",
  "Ulica Jurja Habdelića",
  "Ulica Pavla Radića",
  "Ulica sv. Ćirila i Metoda",
  "Ulica Tita Brezovačkoga",
  "Visoka ulica",
  "Vitezovićeva ulica",
] as const;

export const PARKING_ZONE_2_STREETS = [
  "Aleja pomoraca",
  "Avenija Dubrovnik",
  "Avenija Marina Držića",
  "Avenija Većeslava Holjevca",
  "Bednjanska ulica",
  "Belečka ulica",
  "Benkovićeva ulica",
  "Bisačka ulica",
  "Bistrička ulica",
  "Bleiweisova ulica",
  "Bosutska ulica",
  "Božidarevićeva ulica",
  "Breznička I.",
  "Breznička II.",
  "Brijunska ulica",
  "Brodograditeljska aleja",
  "Bukovačka cesta",
  "Cernička ulica",
  "Crni put",
  "Čazmanska ulica",
  "Čerinina ulica",
  "Čiovska ulica",
  "Čučerska ulica",
  "Dobranska ulica",
  "Doljani",
  "Domobranska ulica",
  "Donji prečac",
  "Drenovačka ulica",
  "Dubravkin trg",
  "Dubravska ulica",
  "Duknovićeva ulica",
  "Dvorište",
  "Fijanova ulica",
  "Froudeova ulica",
  "Gacka ulica",
  "Galovačka ulica",
  "Galovićeva ulica",
  "Garićgradska ulica",
  "Gorjanska ulica",
  "Gornji prečac",
  "Gradišćanska ulica",
  "Granešinska ulica",
  "Gruška ulica",
  "Hvarska ulica",
  "I. Jordanovački odvojak",
  "Ilica (zona II: od Ulice Republike Austrije do Selske ceste)",
  "Iločka ulica",
  "Jankovačka ulica",
  "Japranska ulica",
  "Jelaspoljska ulica",
  "Jordanovac",
  "Jordanovačke livade I.",
  "Jordanovačke livade II.",
  "Kalnička ulica",
  "Kamengradska ulica",
  "Karašička ulica",
  "Klanjčić",
  "Klovićeva ulica",
  "Kninski trg",
  "Koranska ulica",
  "Korčulanska ulica",
  "Kornatska ulica",
  "Koturaška cesta",
  "Kozarčaninova ulica",
  "Krapinska ulica",
  "Krbavska ulica",
  "Krčka ulica",
  "Krivajska ulica",
  "Kruge",
  "Kuhačeva ulica",
  "Kuniščak",
  "Kupska ulica",
  "Lastovska ulica",
  "Lička ulica",
  "Livadarski put",
  "Loborska ulica",
  "Lopudska ulica",
  "Lukavečka ulica",
  "Magazinska cesta",
  "Maksimirska cesta",
  "Mandaličina ulica",
  "Međimurska ulica",
  "Metalčeva ulica",
  "Miljackina ulica",
  "Miramarska cesta",
  "Miramarski podvožnjak",
  "Mirnovac",
  "Mljetska ulica",
  "Mrežnička ulica",
  "Murterska ulica",
  "Nad lipom",
  "Nalješkovićeva ulica",
  "Naselak",
  "Nova cesta",
  "Novska ulica",
  "Njivice",
  "Njivice I.",
  "Njivice II.",
  "Njivice III.",
  "Njivice IV.",
  "Njivice V.",
  "Njivice VI.",
  "Olipska ulica",
  "Orljavička ulica",
  "Osredak",
  "Palić",
  "Palić mali",
  "Park Stara Trešnjevka",
  "Paromlinska cesta",
  "Paška ulica",
  "Pašmanska ulica",
  "Pelješka ulica",
  "Pile I.",
  "Pile II.",
  "Pile III.",
  "Plitvička ulica",
  "Plivska ulica",
  "Poljička ulica",
  "Prilaz baruna Filipovića",
  "Prilaz Ivana Visina",
  "Prilaz Vladislava Brajkovića",
  "Prilesje",
  "Privlačka ulica",
  "Radnička cesta",
  "Radonjska ulica",
  "Radučka ulica",
  "Ramska ulica",
  "Rapska ulica",
  "Reljkovićeva ulica",
  "Resnička ulica",
  "Resselova ulica",
  "Retkovečka ulica",
  "Rujnička ulica",
  "Ružmarinka",
  "Savska cesta (zona II: od Jukićeve ulice do Slavonske avenije)",
  "Selska cesta",
  "Sesvetska ulica",
  "Siget",
  "Slavonska avenija",
  "Slovenska ulica",
  "Sortina ulica",
  "Sprečka ulica",
  "Stara Peščenica II.",
  "Stara Peščenica IV.",
  "Stara Peščenica V.",
  "Strojarska cesta",
  "Supilova ulica",
  "Sutlanska ulica",
  "Svetice",
  "Šarengradska ulica",
  "Šestinski dol",
  "Šetalište Jurija Gagarina",
  "Šipanska ulica",
  "Šoltanska ulica",
  "Šumetlička ulica",
  "Tenjska ulica",
  "Trakošćanska ulica",
  "Tratinska ulica",
  "Trešnjevački trg",
  "Trg Dražena Petrovića",
  "Trg Francuske Republike",
  "Trg Johna Fitzgeralda Kennedyja",
  "Trg kardinala Franje Šepera",
  "Trg Krešimira Ćosića",
  "Trg Luke Botića",
  "Trg Nevenke Topalušić",
  "Trg Otokara Keršovanija",
  "Trg senjskih uskoka",
  "Trg Stjepana Radića",
  "Trg svetog križa",
  "Trg Vlaha Bukovca",
  "Trnjanska cesta",
  "Trnjanska Savica",
  "Trnjanski zavoj I.",
  "Trnjanski zavoj II.",
  "Trnjanski zavoj III.",
  "Trnjanski zavoj IV.",
  "Trpinjska ulica",
  "Tržnica Savica",
  "Tržnica Trešnjevka",
  "Ugljanska ulica",
  "Ukrinska ulica",
  "Ulica Adama Mandrovića",
  "Ulica Alberta Ognjana Štrige",
  "Ulica Alexandera von Humboldta",
  "Ulica Andrije Čubranovića",
  "Ulica Andrije Žaje",
  "Ulica Antuna Nemčića",
  "Ulica Armina Šrapca",
  "Ulica Augusta Harambašića",
  "Ulica Bele Čikoša",
  "Ulica Blaža Lorkovića",
  "Ulica Bogoslava Šuleka",
  "Ulica Božidara Adžije",
  "Ulica Celestina Medovića",
  "Ulica Cvijete Zuzorić",
  "Ulica Dinka Ranjine",
  "Ulica Divka Budaka",
  "Ulica dr. Pavla Markovca",
  "Ulica Dragice Hotko",
  "Ulica Dragojla Kušlana",
  "Ulica Dragutina Domjanića",
  "Ulica Dragutina Hirca",
  "Ulica Dragutina Rakovca",
  "Ulica Eugena Podaubskoga",
  "Ulica Fausta Vrančića",
  "Ulica Ferde Kovačevića",
  "Ulica Ferde Livadića",
  "Ulica Ferde Rusana",
  "Ulica Filipa Vukasovića",
  "Ulica Florijana Andrašeca",
  "Ulica Frana Bošnjakovića",
  "Ulica Frana Folnegovića",
  "Ulica Frana Kesterčaneka",
  "Ulica Franje Krežme",
  "Ulica Franje Petračića",
  "Ulica Franje Pokornoga",
  "Ulica Franje Žigrovića",
  "Ulica Gaje Alage",
  "Ulica Gjure Čanića",
  "Ulica Gjure Eisenhutha",
  "Ulica Gjure Szaba",
  "Ulica Gjure Szaba odvojak",
  "Ulica grada Mainza",
  "Ulica grada Vukovara",
  "Ulica Hermana Bužana",
  "Ulica Hrvatske bratske zajednice",
  "Ulica Huga Badalića",
  "Ulica Ivana Broza",
  "Ulica Ivana Bunića Vučića",
  "Ulica Ivana Lučića",
  "Ulica Ivana Metelka",
  "Ulica Ivana Padovca",
  "Ulica Ivana Rendića",
  "Ulica Ivana Stožira",
  "Ulica Ivana Trnskoga",
  "Ulica Ivana Zahara",
  "Ulica Janka Grahora",
  "Ulica Janka Vukovića",
  "Ulica Josipa Fona",
  "Ulica Josipa Hanuša",
  "Ulica Josipa Pasarića",
  "Ulica Josipa Račića",
  "Ulica Josipa Sermagea",
  "Ulica Klementa Crnčića",
  "Ulica kralja Zvonimira (zona II: od Ulice Vjekoslava Heinzela do Trga J. F. Kennedyja)",
  "Ulica Krste Pavletića",
  "Ulica Lavoslava Ružičke",
  "Ulica Lavoslava Švarca",
  "Ulica Lavoslava Vukelića",
  "Ulica Ljerke Šram",
  "Ulica Ljubomira Marakovića",
  "Ulica Ljudevita Jonkea",
  "Ulica Mate Ujevića",
  "Ulica Matije Smodeka",
  "Ulica Matije Valjavca",
  "Ulica Matka Talovca",
  "Ulica Mavra Vetranića",
  "Ulica Meda Pucića",
  "Ulica Metela Ožegovića",
  "Ulica Milana Ogrizovića",
  "Ulica Miroslava Kraljevića",
  "Ulica Nikole Mašića",
  "Ulica Nikole Škrlca",
  "Ulica Ognjeslava Utješenovića",
  "Ulica Otona Kučere",
  "Ulica Paule i Većeslava Pavleka Miškine",
  "Ulica Pavla Štoosa",
  "Ulica Pere Budmanija",
  "Ulica Petra Grgeca",
  "Ulica Petra Hektorovića",
  "Ulica Petra Petrovića Njegoša",
  "Ulica Petra Sorkočevića",
  "Ulica Petra Zoranića",
  "Ulica Republike Austrije",
  "Ulica Rikarda Katalinića Jeretova",
  "Ulica Rudolfa Valdeca",
  "Ulica Silvija Strahimira Kranjčevića",
  "Ulica Spiridiona Brusine",
  "Ulica Šiška Menčetića",
  "Ulica Tome Blažeka",
  "Ulica Velimira Kljaića",
  "Ulica Veselka Tenžere",
  "Ulica Viktora Cara Emina",
  "Ulica Vinka Jeđuta",
  "Ulica Vjekoslava Babukića",
  "Ulica Vjekoslava Karasa",
  "Ulica Vjekoslava Novotnija",
  "Ulica Vladimira Preloga",
  "Ulica Vladimira Ruždjaka",
  "Ulica Zinke Kunc",
  "Ulica Zvonimira Rihtmana",
  "Ulica Zvonimira Rogoza",
  "Ulica Željka Maričića",
  "Unačka ulica",
  "Unska ulica",
  "Vinogradska cesta",
  "Vodovodna ulica",
  "Vranovina",
  "Vranovinski ogranak I.",
  "Vranovinski ogranak II.",
  "Vrbanjska ulica",
  "Vrbaska ulica",
  "Vrbik",
  "Vrbik I.",
  "Vrbik II.",
  "Vrbik III.",
  "Vrbik IV.",
  "Vrbik V.",
  "Vrbik VI.",
  "Vrbik X.",
  "Vrbik XI.",
  "Vrbik XII.",
  "Vrbik XIII.",
  "Vrtić I.",
  "Vrtić II.",
  "Vučanska ulica",
  "Zavrtnica (zona II: od Ulice kneza Branimira do Ulice Ivana Zahara)",
  "Zeleni trg",
  "Zelinska ulica",
  "Zlarinska ulica",
  "Zlatarićev prilaz",
  "Zmajanska ulica",
  "Zrmanjska ulica",
  "Zrmanjski ogranak",
  "Zvonigradska ulica",
  "Zvornička ulica",
  "Dobri dol",
  "Gorjanovićeva ulica",
  "Ulica Mije Kišpatića",
  "Lukovac",
  "Podvršje",
] as const;

export const PARKING_ZONE_3_STREETS = [
  "Aleja Vlade Antolića",
  "Barčev trg",
  "Cvjetna cesta",
  "Cvjetno naselje I.",
  "Cvjetno naselje II.",
  "Cvjetno naselje III.",
  "Cvjetno naselje IV.",
  "Dankovečka ulica",
  "Hrastin prilaz",
  "Koledinečka ulica",
  "Lomnička ulica",
  "Odranska ulica",
  "Pakoštanska ulica",
  "Prisavlje",
  "Rugvička ulica",
  "Savska cesta (zona III: od Slavonske avenije do Veslačke ulice)",
  "Stupnička ulica",
  "Trnjanska struga VI.",
  "Tržnica Dubrava",
  "Tržnica Jarun",
  "Tržnica Špansko",
  "Tržnica Utrina",
  "Ulica Hrvoja Macanovića",
  "Ulica Josipa Kotnika",
  "Ulica Josipa Marohnića",
  "Veslačka ulica",
  "Kašinska cesta",
  "Ninska ulica",
  "Rimski put",
  "Trg Dragutina Domjanića",
  "Ulica 144. brigade Hrvatske vojske",
  "Ulica Borisa Papandopula",
  "Ulica Borisa Ulricha",
  "Ulica Brune Bjelinskog",
  "Ulica Dragana Plamenca",
  "Ulica Huberta Pettana",
  "Ulica Ivana Brkanovića",
  "Ulica Ivana Grbavca",
  "Ulica Ivane Lang",
  "Ulica Ive Paraća",
  "Ulica Krešimira Kovačevića",
  "Ulica Ladislava Šabana",
  "Ulica Ljudevita Posavskog (zona III: Sesvete)",
  "Ulica Mladena Pozajića",
  "Ulica Petra Dumičića",
  "Ulica Rudolfa Matza",
  "Ulica Stjepana Šuleka",
  "Ulica Vladimira Stahuljaka",
] as const;

export const PARKING_ZONE_4_1_STREETS = [
  "Zagrebački velesajam - istok",
  "Parkirališta kod Terminala Dubrava (Avenija Gojka Šuška)",
  "Parkiralište uz Teniski centar Maksimir (Ulica XI. Ravnice)",
] as const;

export const PARKING_ZONE_4_2_STREETS = [
  "Parkiralište Strojarska cesta (kompleks Gredelj)",
  "Parkiralište Bednjanska / Unska ulica",
  "Parkirališta uz Radničku cestu (Frana Folnegovića - Vjekoslava Heinzela)",
] as const;
